version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_ROOT_PASSWORD=root
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=Leadec123!
      
    networks:
      - cloud-network
    volumes:
      - db-volume:/var/lib/postgres/data
    
  web:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud.domain.com
    links:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Leadec123!
      
    networks:
      - cloud-network
    ports:
      - 8080:80
    volumes:
      - cloud-volume:/var/www/html
    depends_on:
      - db


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - cloud-network
    depends_on:
      - db




networks:
    cloud-network:
        driver: bridge

volumes:
    cloud-volume:
    db-volume: